---
title: "Estatística Computacional"
author: "Prof. Dr. Juliano Bortolini"
date: ""
output: html_document
---

*Bacharelado em Estatístida - UFMT*

*Período letivo: 2024/1*


### Avisos:

- Última atualização do site às **`r format(Sys.time(), "%H:%M")`** do dia **`r format(Sys.time(), "%d/%m/%Y")`**.
- Monitores: Georgiano e Edimar
- [Whatsapp da disciplina]()
- **Notas e frequências disponíveis no Portal do Aluno**


### Ementa:

Geração de realizações de variáveis aleatórias uniformes. Geração de realizações de variáveis aleatórias não-uniformes. Método de Monte Carlo. Métodos de reamostragem. Métodos de otimização numérica.

### Notas de aula:

- Aula 1: apresentação da disciplina e geração de variáveis aleatórias unifome.

- [Lista 1](eclista1.html): exercícios diversos sobre o R.

- [Aula 2](aulas/aula2.html): geração de variáveis aleatórias no R. Método da transformação inversa (v.a. contínuas) e exercícios.

- Lista 2: capítulo 3 do livro da Maria Rizzo e capítulos 3, 4 e 5 do livro do Sheldon Ross.

- [Aula 3](aulas/aula3.html): geração de variáveis aleatórias no R. Método da transformação inversa (v.a. discretas) e exercícios.

- [Aula 4](aulas/aula4.html): tópicos adicionais sobre geração de variáveis aleatórias.

- [Aula 5](aulas/aula5.html): tópicos adicionais sobre geração de variáveis aleatórias.

- Aula 6: prova 1.

- Aula 7: não teve aula.

- Monitoria: resolução da prova 1 com o monitor Georgiano.

- [Aula 8](aulas/aula8.html): método de Monte Carlo. 

- Aula 9: método de Monte Carlo em inferência.

- Lista 3: capítulos 6 e 7 do livro da Maria Rizzo.

- Aula 10: métodos de reamostragem: bootstrap. Motivação para usar bootstrap. População, amostra, parâmetro, estimador, estimativa pontual e intervalar. Bootstrap não paramétrico. Exemplo de bootstrap para média. Intervalo de confiança percentil. Exemplo de bootstrap para correlação.

- Lista 4: capítulos 8 e 9 do livro da Maria Rizzo.

- Aula 11: métodos de reamostragem: um pouco mais sobre bootstrap e jackknife.

- Aula 12: exercícios sobre bootstrap e jackknife.

- Aula 13: prova 2.

- Aula 14: participação na semana da estatística.

- Aula 15: métodos de otimização numérica.



### Avaliação:


*Os critérios de avaliação seguem a Resolução CONSEPE 63/2018.*


2 avaliações (com pontuação de 0 a 10):

  - A1: geração de realizações de variáveis aleatórias.
  - A2: método de Monte Carlo, métodos de reamostragem e métodos de otimização numérica.

O aluno que tiver a nota final, definida pela média aritmética das notas das 2 avaliações, maior ou igual a 5 estará aprovado. **Não há prova final.**

Faltas superiores a 16 horas (equivalente a 4 aulas) implicam em reprovação por falta.

Solicitações de segunda chamada para as provas serão avaliadas conforme o disposto no art. 80 da Res. Consepe nº 14/1999 e art. 8º da Res. Consepe nº 27/1999. Clique [aqui](https://ufmt.br/unidade/estudante/graduacao/pagina/requerimentos/188) para mais informações sobre segunda chamada.

### Livro texto:

-   Maria L. Rizzo. **Statistical Computing with R** Chapman & Hall/CRC. 2019.

### Livro complementar:

-   Sheldon M. Ross. **Simulation** Academic Press. 2006.





----------
<div style="text-align: center;">

[@profjulianobortolini](https://instagram.com/profjulianobortolini) \  \  \ [www.julianobortolini.com.br](http://www.julianobortolini.com.br) \  \  \ [linkedin](https://linkedin.com/in/julianobortolini) \  \  \   [github](https://github.com/julianobortolini) \  \  \   [lattes](http://lattes.cnpq.br/6210909768845403)

</div>


